# Generated by Django 2.0.3 on 2018-03-11 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('base_fiat', models.CharField(default='NZD', max_length=3)),
                ('cc_ETH', models.BooleanField(default=True)),
                ('cc_BTC', models.BooleanField(default=False)),
                ('cc_LTC', models.BooleanField(default=False)),
                ('cc_XRP', models.BooleanField(default=False)),
                ('cc_BCH', models.BooleanField(default=False)),
                ('cc_ETC', models.BooleanField(default=False)),
                ('cc_TRX', models.BooleanField(default=False)),
                ('cc_EOS', models.BooleanField(default=False)),
                ('cc_NEO', models.BooleanField(default=False)),
                ('cc_XMR', models.BooleanField(default=False)),
            ],
        ),
    ]
