# Generated by Django 2.0.3 on 2018-03-11 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Portfolio'),
        ),
    ]
