# Generated by Django 2.0.3 on 2018-03-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180310_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cc_BTC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cc_ETH',
            field=models.BooleanField(default=False),
        ),
    ]
