# Generated by Django 2.0.3 on 2018-03-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180311_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
