# Generated by Django 2.0.3 on 2018-03-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180310_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='base_crypto',
        ),
    ]
